# Generated by Django 4.1.9 on 2023-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Post',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
