# Generated by Django 4.1.9 on 2023-08-08 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_employee_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='officename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Office_name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officeuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
