Employee =[
  {
    "Employee_Name": "Harilal Soren",
    "Date_of_Birth": "07.03.1969",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Karmatar",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Jamtara"
  },
  {
    "Employee_Name": "Nindol Soren",
    "Date_of_Birth": "22.09.1969",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Jamtara",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Karmatar"
  },
  {
    "Employee_Name": "Parmeshwar Rajak",
    "Date_of_Birth": "01.01.1969",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Jamtara",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Karmatar"
  },
  {
    "Employee_Name": "Vanshidhar Rajak",
    "Date_of_Birth": "08.03.1969",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Jamtara",
    "Current_Posting_Year": "3 Year 4 Month",
    "First_Previous_Block": "Fatehpur"
  },
  {
    "Employee_Name": "Hemlal Hansda",
    "Date_of_Birth": "13.02.1964",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Fatehpur",
    "Current_Posting_Year": "3 Year 4 Month",
    "First_Previous_Block": "Jamtara"
  },
  {
    "Employee_Name": "Santosh Kumar Mandal",
    "Date_of_Birth": "06.06.1966",
    "Home_Block": "Kundahit",
    "Current_Posting_Block": "Jamtara",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Fatehpur"
  },
  {
    "Employee_Name": "Nandlal Soren",
    "Date_of_Birth": "18.07.1966",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Karmatar",
    "Current_Posting_Year": "5 Year 11 Month",
    "First_Previous_Block": "Nala"
  },
  {
    "Employee_Name": "Ganesh Prashad Singh",
    "Date_of_Birth": "05.01.1967",
    "Home_Block": "Shikaripada (Dumka)",
    "Current_Posting_Block": "Kundahit",
    "Current_Posting_Year": "3 Year 4 Month",
    "First_Previous_Block": "Nala"
  },
  {
    "Employee_Name": "Kishor Kumar Kha",
    "Date_of_Birth": "19.11.1964",
    "Home_Block": "Jamtara",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "7 Year 2 Month",
    "First_Previous_Block": "Kundahit"
  },
  {
    "Employee_Name": "Bharat Dehri",
    "Date_of_Birth": "03.01.1969",
    "Home_Block": "Dumka",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "2 Year",
    "First_Previous_Block": "Kundahit"
  },
  {
    "Employee_Name": "Niranjan Kumar Yadav",
    "Date_of_Birth": "05.02.1967",
    "Home_Block": "Nala",
    "Current_Posting_Block": "Karmatar",
    "Current_Posting_Year": "5 Year 4 Month",
    "First_Previous_Block": "Fatehpur"
  },
  {
    "Employee_Name": "Ubilal Hembram",
    "Date_of_Birth": "05.11.1969",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Kundahit",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Jamtara"
  },
  {
    "Employee_Name": "Aniruddha Sen",
    "Date_of_Birth": "02.06.1967",
    "Home_Block": "Jamtara",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Fatehpur"
  },
  {
    "Employee_Name": "Praveen Kumar Ray",
    "Date_of_Birth": "17.04.1965",
    "Home_Block": "Karmatar",
    "Current_Posting_Block": "Karmatar",
    "Current_Posting_Year": "4 Year 3 Month",
    "First_Previous_Block": "Kundahit"
  },
  {
    "Employee_Name": "Ravindranath Singh",
    "Date_of_Birth": "25.11.1967",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Nala",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Kundahit"
  },
  {
    "Employee_Name": "Vinay Kant Jha",
    "Date_of_Birth": "21.11.1967",
    "Home_Block": "Fatehpur",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Nala"
  },
  {
    "Employee_Name": "Kartik Rajak",
    "Date_of_Birth": "15.06.1969",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Jamtara",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Nala"
  },
  {
    "Employee_Name": "Kamal Chandra Mahato",
    "Date_of_Birth": "10.11.1967",
    "Home_Block": "Fatehpur",
    "Current_Posting_Block": "Nala",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Narayanpur"
  },
  {
    "Employee_Name": "Gandhi Kisku",
    "Date_of_Birth": "03.01.1971",
    "Home_Block": "Jamtara",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Kundahit"
  },
  {
    "Employee_Name": "Krishnapada Patar",
    "Date_of_Birth": "02.01.1968",
    "Home_Block": "Kundahit",
    "Current_Posting_Block": "Fatehpur",
    "Current_Posting_Year": "2 Year 11 Month",
    "First_Previous_Block": "Narayanpur"
  },
  {
    "Employee_Name": "Munu Murmu",
    "Date_of_Birth": "15.06.1972",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Nala",
    "Current_Posting_Year": "5 Year",
    "First_Previous_Block": "Narayanpur"
  },
  {
    "Employee_Name": "Praphull Kumar Maji",
    "Date_of_Birth": "02.02.1968",
    "Home_Block": "Nala",
    "Current_Posting_Block": "Kundahit",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Jamtara"
  },
  {
    "Employee_Name": "Munsi Murmu",
    "Date_of_Birth": "16.07.1965",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Nala",
    "Current_Posting_Year": "5 Year",
    "First_Previous_Block": "Fatehpur"
  },
  {
    "Employee_Name": "Krishna Kumar Mandal",
    "Date_of_Birth": "09.04.1968",
    "Home_Block": "Nala",
    "Current_Posting_Block": "Karmatar",
    "Current_Posting_Year": "5 Year",
    "First_Previous_Block": "Jamtara"
  },
  {
    "Employee_Name": "Ashok Kumar Chaudhary",
    "Date_of_Birth": "11.03.1965",
    "Home_Block": "Siwan (Bihar)",
    "Current_Posting_Block": "Jamtara",
    "Current_Posting_Year": "5 Year",
    "First_Previous_Block": "Fatehpur"
  },
  {
    "Employee_Name": "Siddheswar Kha",
    "Date_of_Birth": "02.01.1969",
    "Home_Block": "Nala",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Kundahit"
  },
  {
    "Employee_Name": "Sahadev Murmu",
    "Date_of_Birth": "14.06.1970",
    "Home_Block": "Jamtara",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "4 Year",
    "First_Previous_Block": "Nala"
  },
  {
    "Employee_Name": "Haradhan Maji",
    "Date_of_Birth": "07.06.1969",
    "Home_Block": "Jamtara",
    "Current_Posting_Block": "Karmatar",
    "Current_Posting_Year": "5 Year 1 Month",
    "First_Previous_Block": "Kundahit"
  },
  {
    "Employee_Name": "Hopna Hembram",
    "Date_of_Birth": "01.01.1966",
    "Home_Block": "Jamtara",
    "Current_Posting_Block": "Narayanpur",
    "Current_Posting_Year": "5 Year",
    "First_Previous_Block": "Nala"
  },
  {
    "Employee_Name": "MD Sanaul Ansari",
    "Date_of_Birth": "12.09.1965",
    "Home_Block": "Narayanpur",
    "Current_Posting_Block": "Karmatar",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Jamtara"
  },
  {
    "Employee_Name": "Sudhir Kumar Mahato",
    "Date_of_Birth": "04.01.1968",
    "Home_Block": "Jamtara",
    "Current_Posting_Block": "Fatehpur",
    "Current_Posting_Year": "3 Year",
    "First_Previous_Block": "Narayanpur"
  }
]





















# Employee =[
#   {
#     "GPF_No": "JMT/COLL/06",
#     "Name": "Dayashankar Jha",
#     "Designation": "OS",
#     "Curr_office": "District Land Acquisition Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2020",
#     "First_post_office": "Block Development Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "District Revenue Section Jamtara",
#     "Second_post_office_block" : "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/84",
#     "Name": "Lakhindra Hembram",
#     "Designation": "OS",
#     "Curr_office": "District General Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2020",
#     "First_post_office": "Circle Office Kundahit",
#     "First_post_office_block": "Kundahit",
#     "Second_post_office": "Circle Office Nala",
#     "Second_post_office_block": "Nala",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/188",
#     "Name": "Rajendra Murmu",
#     "Designation": "HC",
#     "Curr_office": "District Development Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Jamtara",
#     "First_post_office_block": "Jamtara",
#     "Second_post_office": "District Nilam Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/191",
#     "Name": "Rambilash Pandit",
#     "Designation": "HC",
#     "Curr_office": "District Panchayat Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2018",
#     "First_post_office": "District Land Reforms Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Nazarat Section Jamtara",
#      "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/139",
#     "Name": "Amarjeet Hembram",
#     "Designation": "HC",
#     "Curr_office": "District Treasury Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2017",
#     "First_post_office": "District Establishment Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Circle Office Jamtara",
#     "Second_post_office_block": "Jamtara",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/PAR/272",
#     "Name": "Uday Shankar Gorai",
#     "Designation": "HC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office",
#     "First_post_office_block": "Narayanpur",
#     "Second_post_office": "District Election Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "Additional District Transport Office Jamtara",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "DUM/PAR/276",
#     "Name": "Baiju Jha",
#     "Designation": "HC",
#     "Curr_office": "District Planning Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "DRDA Office, Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "Additional Sports Office and District Social Security Office",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "DUM/RDD/657",
#     "Name": "Ranjeet Kumar Sinha",
#     "Designation": "HC",
#     "Curr_office": "Block Development Office Jamtara",
#     "Curr_block": "Jamtara",
#     "Curr_post_year": "2018",
#     "First_post_office": "District Land Reforms Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Legal Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/182",
#     "Name": "Goutam Kumar Choubey",
#     "Designation": "HC",
#     "Curr_office": "Block Development Office Narayanpur",
#     "Curr_block": "Narayanpur",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Treasury Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Acquisition Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/WEL/167",
#     "Name": "Sukdev Das",
#     "Designation": "HC",
#     "Curr_office": "Block Development Office Nala",
#     "Curr_block": "Nala",
#     "Curr_post_year": "2019",
#     "First_post_office": "DC Confidential Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Acquisition Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/181",
#     "Name": "Sanjit Dan",
#     "Designation": "HC",
#     "Curr_office": "Block Development Office Kundahit",
#     "Curr_block": "Kundahit",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Narayanpur",
#     "First_post_office_block": "Narayanpur",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/185",
#     "Name": "Samir Kumar",
#     "Designation": "HC",
#     "Curr_office": "Block Development Office Karmatanr",
#     "Curr_block": "Karmatanr",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Nilam Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Block Development Office Nala",
#     "Second_post_office_block": "Nala",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/RDD/973",
#     "Name": "Rajesh Kumar",
#     "Designation": "HC",
#     "Curr_office": "Block Development Office Fatehpur",
#     "Curr_block": "Fatehpur",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Narayanpur",
#     "First_post_office_block": "Narayanpur",
#     "Second_post_office": "District Consumer Form Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/190",
#     "Name": "Kamal Kishor Das",
#     "Designation": "HC",
#     "Curr_office": "Circle Office Jamtara",
#     "Curr_block": "Jamtara",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Panchayat Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Circle Office",
#     "Second_post_office_block": "Nala",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/183",
#     "Name": "Ajay Kumar Das",
#     "Designation": "HC",
#     "Curr_office": "Circle Office Nala",
#     "Curr_block": "Nala",
#     "Curr_post_year": "2016",
#     "First_post_office": "District Treasury Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Acquisition Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/PAR/271",
#     "Name": "Md. Abrar Ahmad khan",
#     "Designation": "HC",
#     "Curr_office": "Circle Office Kundahit",
#     "Curr_block": "Kundahit",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/179",
#     "Name": "Baidhnath Hansda",
#     "Designation": "HC",
#     "Curr_office": "Circle Office Karmatanr",
#     "Curr_block": "Karmatanr",
#     "Curr_post_year": "2016",
#     "First_post_office": "Block Development Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "Circle Office Narayanpur",
#     "Second_post_office_block": "Narayanpur",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/1",
#     "Name": "Azad Murmu",
#     "Designation": "HC",
#     "Curr_office": "Circle Office Fatehpur",
#     "Curr_block": "Fatehpur",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Establishment Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Block Development Office Nala",
#     "Second_post_office_block": "Nala",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/123",
#     "Name": "Binita Murmu",
#     "Designation": "HC",
#     "Curr_office": "District Land Reforms Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Jamtara",
#     "First_post_office_block": "Jamtara",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/161",
#     "Name": "Lisen Tudu",
#     "Designation": "HC",
#     "Curr_office": "District Record Room Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Circle Office Kundahit",
#     "First_post_office_block": "Kundahit",
#     "Second_post_office": "Circle Office Jamtara",
#     "Second_post_office_block": "Jamtara",
#     "Dept_office": "",
#     "Dept_block": ""
#   },

#   {
#     "GPF_No": "JMT/COLL/N04",
#     "Name": "Jyoti Bandana",
#     "Designation": "UDC",
#     "Curr_office": "District Nilam Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": " District DC Confidential Section Jamtara ",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District General Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "GOD/COLL/5",
#     "Name": "Manoj Kumar Murmu",
#     "Designation": "UDC",
#     "Curr_office": "District Nazarat Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Development Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "DC Confidential Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N11",
#     "Name": "Amardip Kumar",
#     "Designation": "UDC",
#     "Curr_office": "District Election Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Sub Divisional Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Acquisition Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "Additional District Land Acquisition Office Jamtara",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "JMT/COLL/N28",
#     "Name": "Sabita Kumari",
#     "Designation": "UDC",
#     "Curr_office": "District General Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Land Acquisition Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DEO/PAR/240",
#     "Name": "Krishna Tudu",
#     "Designation": "UDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Narayanpur",
#     "First_post_office_block": "Narayanpur",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N12",
#     "Name": "Meena Pujhar",
#     "Designation": "UDC",
#     "Curr_office": "District Land Acquisition Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Land Reforms Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N37",
#     "Name": "Ankita Shekhar",
#     "Designation": "UDC",
#     "Curr_office": "Block Development Office Jamtara",
#     "Curr_block": "Jamtara",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Jamtara",
#     "First_post_office_block": "Jamtara",
#     "Second_post_office": "District General Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "GOD/COLL/40",
#     "Name": "Nirmal Kumar Murmu",
#     "Designation": "UDC",
#     "Curr_office": "Block Development Office Narayanpur",
#     "Curr_block": "Narayanpur",
#     "Curr_post_year": "2017",
#     "First_post_office": "District Land Acquisition Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N34",
#     "Name": "Rajeev Kumar Dehri",
#     "Designation": "UDC",
#     "Curr_office": "Block Development Office Kundahit",
#     "Curr_block": "Kundahit",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "Circle Office Kundahit",
#     "Second_post_office_block": "Kundahit",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/194",
#     "Name": "Vinay Kant Murmu",
#     "Designation": "UDC",
#     "Curr_office": "Block Development Office Karmatanr",
#     "Curr_block": "Karmatanr",
#     "Curr_post_year": "2018",
#     "First_post_office": "Circle Office Narayanpur",
#     "First_post_office_block": "Narayanpur",
#     "Second_post_office": "Block Development Office Fatehpur",
#     "Second_post_office_block": "Fatehpur",
#     "Dept_office": "District Transport Office Jamtara",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "JMT/COLL/N35",
#     "Name": "Binti Devi",
#     "Designation": "UDC",
#     "Curr_office": "Circle Office Jamtara",
#     "Curr_block": "Jamtara",
#     "Curr_post_year": "2017",
#     "First_post_office": "Circle Office Jamtara",
#     "First_post_office_block": "Jamtara",
#     "Second_post_office": "District Establishment Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/29",
#     "Name": "Prakash Kumar Rajak",
#     "Designation": "UDC",
#     "Curr_office": "Circle Office Jamtara",
#     "Curr_block": "Jamtara",
#     "Curr_post_year": "2019",
#     "First_post_office": "Sub Divisional Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Reforms Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/EDN/4182",
#     "Name": "Sushil Kumar Dom",
#     "Designation": "UDC",
#     "Curr_office": "Circle Office Karmatanr",
#     "Curr_block": "Karmatanr",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/195",
#     "Name": "Shiv Kumar Hembram",
#     "Designation": "UDC",
#     "Curr_office": "Sub Divisional Office, Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Panchayat Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Block Development Office Kundahit",
#     "Second_post_office_block": "Kundahit",
#     "Dept_office": "Municipality Office Mihijam",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "DUM/RDD/507",
#     "Name": "Pradip Kumar Rakshit",
#     "Designation": "UDC",
#     "Curr_office": "Sub Divisional Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Sub Divisional Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Circle Office",
#     "Second_post_office_block": "Karmatanr",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N31",
#     "Name": "Suchita kumari",
#     "Designation": "UDC",
#     "Curr_office": "Sub Divisional Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Sub Divisional Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Reforms Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "GOD/COLL/46",
#     "Name": "Sugendra Hembram",
#     "Designation": "UDC",
#     "Curr_office": "Sub Divisional Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2018",
#     "First_post_office": "District General Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Block Development Office Karmatanr",
#     "Second_post_office_block": "Karmatanr",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DEO/PAR/233",
#     "Name": "Suresh Hazra",
#     "Designation": "UDC",
#     "Curr_office": "Sub Divisional Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2017",
#     "First_post_office": "District Panchayat Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Legal Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N32",
#     "Name": "Debashish Singh",
#     "Designation": "UDC",
#     "Curr_office": "Sub Divisional Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "DC Confidential Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Reforms Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/COLL/180",
#     "Name": "Niranjan Murmu",
#     "Designation": "UDC",
#     "Curr_office": "District Land Reforms Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2016",
#     "First_post_office": "District General Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Circle Office Nala",
#     "Second_post_office_block": "Nala",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N07",
#     "Name": "Ratan Pujhar",
#     "Designation": "UDC",
#     "Curr_office": "District Consumer Form Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Supply Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Development Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/REV/N01",
#     "Name": "Jayant Kumar Dey",
#     "Designation": "LDC",
#     "Curr_office": "District Revenue Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Fatehpur",
#     "First_post_office_block": "Fatehpur",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N03",
#     "Name": "Bikas Kumar",
#     "Designation": "LDC",
#     "Curr_office": "District Nazarat Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2017",
#     "First_post_office": "Circle Office Jamtara",
#     "First_post_office_block": "Jamtara",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N02",
#     "Name": "Dindayal Kumar",
#     "Designation": "LDC",
#     "Curr_office": "District Supply Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2018",
#     "First_post_office": "Sub Divisional Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N01",
#     "Name": "Nikhil Kumar",
#     "Designation": "LDC",
#     "Curr_office": "District Treasury Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2018",
#     "First_post_office": "Block Development Office Karmatanr",
#     "First_post_office_block": "Karmatanr",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N08",
#     "Name": "Manoj Kumar Soren",
#     "Designation": "LDC",
#     "Curr_office": "District General Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Revenue Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Land Reforms Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N14",
#     "Name": "Vivek Kumar Dey",
#     "Designation": "LDC",
#     "Curr_office": "District Land Acquisition Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District General Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/AGR/326",
#     "Name": "Jitendra Kumar Singh",
#     "Designation": "LDC",
#     "Curr_office": "Block Development Office Nala",
#     "Curr_block": "Nala",
#     "Curr_post_year": "2019",
#     "First_post_office": "District Development Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Circle Office Narayanpur",
#     "Second_post_office_block": "Narayanpur",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N41",
#     "Name": "Prabhash Kumar",
#     "Designation": "LDC",
#     "Curr_office": "Block Development Office Karmatanr",
#     "Curr_block": "Karmatanr",
#     "Curr_post_year": "2018",
#     "First_post_office": "Block Development Office Kundahit",
#     "First_post_office_block": "Kundahit",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "DUM/REV/457",
#     "Name": "Kalipad Tudu",
#     "Designation": "LDC",
#     "Curr_office": "Block Development Office Fatehpur",
#     "Curr_block": "Fatehpur",
#     "Curr_post_year": "2019",
#     "First_post_office": "Circle Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N51",
#     "Name": "Bhirguwar Jha",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Narayanpur",
#     "Curr_block": "Narayanpur",
#     "Curr_post_year": "2016",
#     "First_post_office": "Circle Office Fatehpur",
#     "First_post_office_block": "Fatehpur",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Gopal Kunjilwal",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Narayanpur",
#     "Curr_block": "Narayanpur",
#     "Curr_post_year": "2016",
#     "First_post_office": "Circle Office Karmatanr",
#     "First_post_office_block": "Karmatanr",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N59",
#     "Name": "Hari Kishor Ray",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Nala",
#     "Curr_block": "Nala",
#     "Curr_post_year": "2019",
#     "First_post_office": "DC Confidential Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Supply Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N58",
#     "Name": "Bhanu Pratap Dehri",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office",
#     "Curr_block": "Nala",
#     "Curr_post_year": "2020",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N23",
#     "Name": "Bhushan Kumar",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Kundahit",
#     "Curr_block": "Kundahit",
#     "Curr_post_year": "2016",
#     "First_post_office": "Sub Divisional Office Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "Circle Office Nala",
#     "Second_post_office_block": "Nala",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Chand Hembram",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Kundahit",
#     "Curr_block": "Kundahit",
#     "Curr_post_year": "2019",
#     "First_post_office": "Block Development Office Karmatanr",
#     "First_post_office_block": "Karmatanr",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N55",
#     "Name": "Nityanand Pandey",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Karmatanr",
#     "Curr_block": "Karmatanr",
#     "Curr_post_year": "2019",
#     "First_post_office": "Circle Office Kundahit",
#     "First_post_office_block": "Kundahit",
#     "Second_post_office": "District General Section Jamtara",
#     "Second_post_office_block" : "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N54",
#     "Name": "Dipak Kumar Jha",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Karmatanr",
#     "Curr_block": "Karmatanr",
#     "Curr_post_year": "2020",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N44",
#     "Name": "Manraj Kuwar",
#     "Designation": "LDC",
#     "Curr_office": "Circle Office Fatehpur",
#     "Curr_block": "Fatehpur",
#     "Curr_post_year": "2016",
#     "First_post_office": "District Revenue Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "JMT/COLL/N24",
#     "Name": "Kishor Kumar Verma",
#     "Designation": "LDC",
#     "Curr_office": "Sub Divisional Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2015",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "Municipality Office Jamtara",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "JMT/COLL/N25",
#     "Name": "Pintu Kumar Maji",
#     "Designation": "LDC",
#     "Curr_office": "Sub Divisional Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2018",
#     "First_post_office": "Circle Office Fatehpur",
#     "First_post_office_block": "Fatehpur",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "District Revenue Section Jamtara",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "JMT/COLL/N21",
#     "Name": "Dinanath Paharia",
#     "Designation": "LDC",
#     "Curr_office": "District Land Reforms Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Circle Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "District Establishment Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "District Establishment Section Jamtara",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "JMT/COLL/N20",
#     "Name": "Rajesh Kumar Marandi",
#     "Designation": "LDC",
#     "Curr_office": "District Land Reforms Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "District General Section Jamtara",
#     "First_post_office_block": "DHQ",
#     "Second_post_office": "District Establishment Section Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "District Social Security Office Jamtara",
#     "Dept_block": "DHQ"
#   },
#   {
#     "GPF_No": "JMT/COLL/N22",
#     "Name": "Prem Prakash Tudu",
#     "Designation": "LDC",
#     "Curr_office": "District Land Reforms Office Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2019",
#     "First_post_office": "Circle Office Nala",
#     "First_post_office_block": "Nala",
#     "Second_post_office": "Sub Divisional Office Jamtara",
#     "Second_post_office_block": "DHQ",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Dinesh Dutta",
#     "Designation": "LDC",
#     "Curr_office": "District Consumer Form Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2022",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Sandeep Kumar Saw",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Vishal Kumar Singh",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Manoj Kumar Paul",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Sanjay Kumar Suman",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Anand Kumar Dey",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Shailesh Das",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Gopal Marandi",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   },
#   {
#     "GPF_No": "",
#     "Name": "Manoj Kumar Saw",
#     "Designation": "LDC",
#     "Curr_office": "District Establishment Section Jamtara",
#     "Curr_block": "DHQ",
#     "Curr_post_year": "2023",
#     "First_post_office": "",
#     "First_post_office_block": "",
#     "Second_post_office": "",
#     "Second_post_office_block": "",
#     "Dept_office": "",
#     "Dept_block": ""
#   }
# ]

